import type { Metadata } from "next";
import { inter } from '@/app/ui/fonts'
import "./globals.css";


export const metadata: Metadata = {
  title: "Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
